- name: Create bastion host
  equinix.metal.device:
    api_token: "{{ equinix_metal_api_key }}"
    project_id: "{{ equinix_metal_project_id }}"
    hostnames: "{{ equinix_metal_hostname_prefix }}-bastion"
    operating_system: "{{ bastion_os }}"
    plan: "{{ bastion_size }}"
    facility: "{{ equinix_metal_facility }}"
    state: active
    tags:
      - "{{ cluster_name }}"
      - "{{ equinix_metal_hostname_prefix }}"
    wait_timeout: 1200
  register: bastion_host

- name: Add bastion host to the inventory
  add_host:
    hostname: bastion
    ansible_host: "{{ bastion_host.devices[0].public_ipv4 }}"
    ansible_user: root

- name: Add bastion fingerprint to known hosts
  connection: local
  shell: |
    ssh-keygen -F {{ hostvars.bastion.ansible_host }} ||
    ssh-keyscan -H {{ hostvars.bastion.ansible_host }} >> ~/.ssh/known_hosts
  register: known_hosts_update
  changed_when: "'found' not in known_hosts_update.stdout"

- name: Install Podman
  package:
    name: podman
    state: present
  delegate_to: bastion

- name: Create Web server directory
  file:
    path: /var/tmp/ai
    state: directory
  delegate_to: bastion

- name: Prepare assisted ISO for iPXE
  containers.podman.podman_container:
    name: assisted_ipxe
    image: quay.io/ohadlevy/ai-ipxe
    env:
      ISO_URL: "{{ iso_download_url }}"
      BASE_URL: "{{ bastion_host.devices[0].private_ipv4 }}"
    volume:
      - /var/tmp/ai:/data:Z
    network: host
    rm: yes
    state: started
  delegate_to: bastion

- name: Start web server
  containers.podman.podman_container:
    name: web_server
    image: bitnami/nginx:latest
    volume:
      - /var/tmp/ai/ipxe:/app:ro
    ports:
      - "{{ bastion_host.devices[0].private_ipv4 }}:80:8080"
    rm: yes
    state: started
  delegate_to: bastion
