---
- name: Single-Node OpenShift (SNO) with GPU on Equinix Metal
  gather_facts: no
  hosts: localhost

  vars:
    cluster_name: gpu-equinix-sno
    temp_directory: "{{ playbook_dir }}/tmp"

  roles:
    - karmab.ansible_aicli_modules

  pre_tasks:

    - name: Install Python prerequisites
      pip:
        name: aicli>=99.0.202205110654.202103111306
        state: present

    - name: Create temp directory
      file:
        path: "{{ temp_directory }}"
        state: directory

  tasks:

    - name: Include global vars
      include_vars:
        file: defaults.yml

    - name: Create assisted cluster
      ai_cluster:
        name: "{{ cluster_name }}"
        state: present
        parameters:
          openshift_version: "{{ openshift_version }}"
          sno: true
          minimal: false
          pull_secret: "{{ pull_secret_path }}"
          base_dns_domain: "{{ openshift_base_domain }}"
          ssh_public_key: "{{ lookup('file', ssh_public_key) }}"
        offlinetoken: "{{ ocm_offline_token }}"

    - name: Read assisted cluster's InfraEnv
      ai_infraenv_info:
        name: "{{ cluster_name }}"
        offlinetoken: "{{ ocm_offline_token }}"
      register: assisted_infraenv

    - name: Provision bastion host
      include_role:
        name: bastion
      vars:
        iso_download_url: "{{ assisted_infraenv.download_url }}"

    - name: Provision control nodes
      include_role:
        name: metal_nodes
      vars:
        machine_size: g2.large.x86 # c3.small.x86 for testing
        roles:
        - sno

    - name: Install OpenShift cluster
      include_role:
        name: assisted_cluster

    - name: Install GPU Operator
      include_role:
        name: openshift-on-vmware-with-vgpu/roles/gpu_operator
      vars:
        openshift_api_vip: "{{ assisted_cluster.api_vip }}"
        gpu_type: gpu