- name: Destroy Equinix nodes
  include_role:
    name: metal_cleanup

- name: Delete assisted cluster
  include_role:
    name: empovit.assisted_openshift.cluster_installation
    tasks_from: cleanup