- name: Provision nodes and boot from iPXE
  equinix.metal.device:
    api_token: "{{ equinix_metal_api_key }}"
    project_id: "{{ equinix_metal_project_id }}"
    hostnames: "{{ [equinix_metal_hostname_prefix] | product(roles) | map('join', '-') }}"
    count: "{{ roles | length }}"
    operating_system: custom_ipxe
    plan: "{{ machine_size }}"
    facility: "{{ equinix_metal_facility }}"
    state: active
    tags:
      - "{{ cluster_name }}"
      - "{{ equinix_metal_hostname_prefix }}"
    wait_timeout: 600
    always_pxe: false
    user_data: |
      #!ipxe

      set dhcp_server {{ bastion_host.devices[0].private_ipv4 }}

      :retry_dhcp
      dhcp
      ping --count 1 ${dhcp_server} && goto install_os || goto retry_dhcp

      :install_os
      set live_url http://{{ bastion_host.devices[0].private_ipv4 }}
      initrd --name main ${live_url}/initrd.img
      kernel ${live_url}/vmlinuz initrd=main ignition.config.url=${live_url}/config.ign coreos.live.rootfs_url=${live_url}/rootfs.img random.trust_cpu=on rd.luks.options=discard ignition.firstboot ignition.platform.id=metal console=tty0 console=ttyS1,115200n8 coreos.inst.persistent-kargs="console=tty0 console=ttyS1,115200n8"
      boot
