# work around the role not handing 'ready'
- name: Wait for cluster to become ready
  ai_cluster_info:
    name: "{{ cluster_name }}"
    offlinetoken: "{{ ocm_offline_token }}"
  register: assisted_cluster
  until: assisted_cluster.status == 'ready' or assisted_cluster.status == 'installed'
  retries: 40
  delay: 30

- name: Install cluster
  ai_cluster:
    name: "{{ cluster_name }}"
    offlinetoken: "{{ ocm_offline_token }}"
    state: installed

- name: Retrieve installed cluster
  ai_cluster_info:
    name: "{{ cluster_name }}"
    offlinetoken: "{{ ocm_offline_token }}"
  register: assisted_cluster

- name: Download cluster kubeconfig
  command: "aicli --token {{ ocm_offline_token }} download kubeconfig --path {{ temp_directory }} {{ assisted_cluster.id }}"

- name: Download cluster password
  command: "aicli --token {{ ocm_offline_token }} download kubeadmin-password --path {{ temp_directory }} {{ assisted_cluster.id }}"

- name: Set kubeconfig path
  set_fact:
    kubeconfig: "{{ temp_directory }}/kubeconfig.{{ assisted_cluster.id }}"

- name: Update kubeconfig permissions
  file:
    path: "{{ kubeconfig }}"
    mode: '600'

- name: Print cluster information
  debug:
    msg:
    - "Assisted cluster ID: {{ assisted_cluster.id }}"
    - "API VIP: {{ assisted_cluster.api_vip }}"
    - "export KUBECONFIG={{ kubeconfig }}"